@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class StatusBarFooter
Class CommandBox
Class ExpandedContactPanel
Class PersonDetailsPanel
Class AttendanceListPanel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" ExpandedContactPanel
MainWindow --> "0..1" HelpWindow

PersonListPanel -down-> "*" PersonCard

ExpandedContactPanel -down-> "1" PersonDetailsPanel

ExpandedContactPanel -down-> "1" AttendanceListPanel

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ExpandedContactPanel --|> UiPart
PersonDetailsPanel --|> UiPart
AttendanceListPanel --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

PersonCard ..> Model
PersonDetailsPanel ..> Model : ""
AttendanceListPanel ..> Model : ""
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

note as N1
  This diagram is intentionally simplified to show only
  high-level UI components. Fine-grained UI classes
  (i.e., PersonCardField, AttendanceCard, AttendanceCardField)
  are omitted as they do not affect the overall UI architecture.
end note

MainWindow -[hidden]-|> UiPart
@enduml
